SELECT CARTS.USER_ID FROM CARTS
JOIN CART_PRODUCTS
ON CART_PRODUCTS.CART_ID = CARTS.ID
WHERE CART_PRODUCTS.NAME = 'Flour'
GROUP BY CARTS.USER_ID;



SELECT DISTINCT CARTS.USER_ID FROM CARTS
JOIN (
    SELECT DISTINCT CART_PRODUCTS.CART_ID
    FROM CART_PRODUCTS
    WHERE NAME = 'Flour'
    ) AS CART_PRODUCT
    ON CART_PRODUCT.CART_ID = CARTS.ID
ORDER BY CARTS.USER_ID;

